apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eft5gqlv3-nodejs 
  janus-idp.io/tekton: eft5gqlv3-nodejs
  backstage.io/kubernetes-id: eft5gqlv3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eft5gqlv3-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  